test coverage

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -16,7 +16,6 @@ jobs:
       - uses: actions/setup-node@v3
         with:
           node-version: '14'
-      - run: env
       - run: npm install -g bats
       - name: BATS tests
         run: bats test
@@ -35,3 +34,43 @@ jobs:
         with:
           check_together: 'yes'
           scandir: './src'
+
+  # https://github.com/bats-core/bats-core/blob/360c1ea5371622132ab669e9cb9687d21298699b/.github/workflows/tests.yml            
+  coverage:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '14'
+      - run: npm install -g bats
+      - run: |
+          wget https://github.com/SimonKagstrom/kcov/releases/download/v40/kcov-amd64.tar.gz
+          tar -xf kcov-amd64.tar.gz
+      - run: |
+          ./usr/local/bin/kcov --exclude-path=/tmp $PWD/coverage bats --filter-tags '!no-kcov' test/
+        shell: 'script -q -e -c "bash {0}"' # work around tty issues
+        env:
+          TERM: linux # fix tput for tty issue work around
+      - name: Archive code coverage results
+        uses: actions/upload-artifact@v3
+        with:
+          name: code-coverage-report
+          path: coverage/*
+      - name: Print the Total Coverage
+        id: coverage-percent
+        shell: bash
+        env:
+          minimum_coverage: 86.39
+        run: |
+          value=$(jq '.percent_covered' <coverage/bats/coverage.json)
+          fixd_point() { # <float val>
+            int=${value%.*}
+            decimals=${value#*.}
+            echo $int${decimals::2}
+          }
+          echo "Coverage: $value%" | tee "$GITHUB_STEP_SUMMARY"
+          if (( $(fixed_point $value) < $(fixed_point $expected) )); then
+            echo "  is below required minimum coverage ($minimum_coverage%)." | tee -a "$GITHUB_STEP_SUMMARY"
+            exit 1
+          fi            
